<?php

//payment channel
defined('TRANSACTION_CHANNEL_PAYPAL') 		or define('TRANSACTION_CHANNEL_PAYPAL','paypal');
defined('TRANSACTION_CHANNEL_EGP') 			or define('TRANSACTION_CHANNEL_EGP','egp');
defined('TRANSACTION_CHANNEL_IDEAL') 		    or define('TRANSACTION_CHANNEL_IDEAL','ideal');
defined('TRANSACTION_CHANNEL_PAGSMILE') 		or define('TRANSACTION_CHANNEL_PAGSMILE','pagsmile');
defined('TRANSACTION_CHANNEL_ASTROPAY') 		or define('TRANSACTION_CHANNEL_ASTROPAY','astropay');
defined('TRANSACTION_CHANNEL_MERCADOPAGO') 	or define('TRANSACTION_CHANNEL_MERCADOPAGO','mercadopago');
defined('TRANSACTION_CHANNEL_ASIABILL') 		or define('TRANSACTION_CHANNEL_ASIABILL','asiabill');
defined('TRANSACTION_CHANNEL_SC') 			or define('TRANSACTION_CHANNEL_SC','sc');
defined('TRANSACTION_CHANNEL_PAYSSION') 			or define('TRANSACTION_CHANNEL_PAYSSION','payssion');

//PAYMENT TYPE
defined('TRANSACTION_TYPE_PAYPAL_PAYPAL') or define('TRANSACTION_TYPE_PAYPAL_PAYPAL','paypal');

defined('TRANSACTION_TYPE_EGP_CREDITCARD') or define('TRANSACTION_TYPE_EGP_CREDITCARD','creditcard');
defined('TRANSACTION_TYPE_EGP_CREDITCARDTOKEN') or define('TRANSACTION_TYPE_EGP_CREDITCARDTOKEN','creditcard-token');

defined('TRANSACTION_TYPE_IDEAL_IDEAL') or define('TRANSACTION_TYPE_IDEAL_IDEAL','ideal');

defined('TRANSACTION_TYPE_PAGSMILE_BOLETO') or define('TRANSACTION_TYPE_PAGSMILE_BOLETO','boleto');
defined('TRANSACTION_TYPE_PAGSMILE_LOTTERY') or define('TRANSACTION_TYPE_PAGSMILE_LOTTERY','lottery');
defined('TRANSACTION_TYPE_PAGSMILE_CREDITCARD') or define('TRANSACTION_TYPE_PAGSMILE_CREDITCARD','creditcard');
defined('TRANSACTION_TYPE_PAGSMILE_FLASHPAY') or define('TRANSACTION_TYPE_PAGSMILE_FLASHPAY','flashpay');

defined('TRANSACTION_TYPE_ASTROPAY_ONLINE') or define('TRANSACTION_TYPE_ASTROPAY_ONLINE','AstropayTransfer');
defined('TRANSACTION_TYPE_ASTROPAY_CASH') or define('TRANSACTION_TYPE_ASTROPAY_CASH','AstropayBoleto');
defined('TRANSACTION_TYPE_ASTROPAY_CREDIT_CARD') or define('TRANSACTION_TYPE_ASTROPAY_CREDIT_CARD','AstropayCreditCard');

defined('TRANSACTION_TYPE_MERCADOPAGO_CREDITCARD') or define('TRANSACTION_TYPE_MERCADOPAGO_CREDITCARD','creditcard');

defined('TRANSACTION_TYPE_ASIABILL_CREDITCARD') or define('TRANSACTION_TYPE_ASIABILL_CREDITCARD','creditcard');
defined('TRANSACTION_TYPE_ASIABILL_CREDITCARDTOKEN') or define('TRANSACTION_TYPE_ASIABILL_CREDITCARDTOKEN','creditcard-token');

defined('TRANSACTION_TYPE_SC_SC') or define('TRANSACTION_TYPE_SC_SC','sc');

//定义风控黑白名单标志
defined('RISK_BLACK_FLAG') OR define('RISK_BLACK_FLAG',1);
defined('RISK_WHITE_FLAG') OR define('RISK_WHITE_FLAG',2);