<?php
namespace app\cic\validate;
use think\Validate;

class Customer extends Validate{
    protected $rule = [
        ['AccountName',     'require|length:1,150',     'AccountName can not null|AccountName Invalid parameter length'],
        ['SiteID',     'number',        "SiteID Must be a number"],
        ['Password',     'length:6,50',                    'Password Invalid parameter length'],
        ['token',     'require|length:6,50',                    'Token can not null|Token Invalid parameter length'],
        ['RegisterStart',     'number|length:1,15',"RegisterStart Must be a number|RegisterStart Length must be between 1-15"],
        ['RegisterEnd',     'number|length:1,15',"RegisterEnd Must be a number|RegisterEnd Length must be between 1-15"],
        ['BirthdayStart',     'number|length:1,15',"BirthdayStart Must be a number|BirthdayStart Length must be between 1-15"],
        ['BirthdayEnd',     'number|length:1,15',"BirthdayEnd Must be a number|BirthdayEnd Length must be between 1-15"],
        ['CountryCode',     'alphaNum|length:1,50',"CountryCode Is not Valid|CountryCode Length must be between 1-50"],
        ['Remarks',     'chsDash|length:1,5000',"Remarks Is not Valid|Remarks Length must be between 1-5000"],
        ['Status',     'number|length:1,10',"Status Must be a number|Status Length must be between 1-10"],
        ['Email',     ['regex'=>"/^(?:[a-zA-Z0-9!#$%&'*+=?\/^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&'*+=?\/^_`{|}~-]+)*|'(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*')@(?:(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-zA-Z0-9-]*[a-zA-Z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])$/"],"Wrong Mail format Or Email's Length Is Invalid."],
        ['FirstName',     'length:1,150',"FirstName Length must be between 1-150"],
        ['LastName',     'length:1,150',"LastName Length must be between 1-150"],
        ['SourceType',     'number|length:1,10',"SourceType Must be a number|SourceType Length must be between 1-10"],
        ['Gender',     'number|in:0,1,2',        "Gender Must be a number|Gender must be between 0, 1, 2"],
        ['PhotoPath',     'length:1,300',        "PhotoPath Length Is Invalid."],
        ['Birthday',     'number|length:1,20',        "Birthday Must be a Number"],
        ['Old_Password',     'length:6,50',        "Old Password Invalid parameter length"],
        ['New_Password',     'length:6,50',        "New Password Invalid parameter length"],
        ['PaymentPassword',     'length:6,50',        "New Password Invalid parameter length"],
        ['ID',     'number|length:1,20',        "ID Must be a number|ID Length must be between 1-20"],
        ['CustomerID',     'number|length:1,20',        "CustomerID Must be a number|CustomerID Length must be between 1-20"],
        ['user_data','require','user_data can not null'],
        ['field_type','require|number','field_type can not null|field_type Must be a number'],
        ['BrowserAttr','length:0,300','BrowserAttr Invalid parameter length'],
        ['BrowserVersion','length:0,300','BrowserVersion Invalid parameter length'],
        ['system','length:0,100','system Invalid parameter length'],
        ['IPAddress','ip',"IPAddress Format error"],
        ['Country','length:0,100',"Country Invalid parameter length"],
        ['Province','length:0,100',"Province Invalid parameter length"],
        ['City','length:0,100',"City Invalid parameter length"],
        ['OperationName',     'require|length:1,150',     'OperationName can not null|OperationName Invalid parameter length'],
        ['DataCategory','length:0,100',"DataCategory Invalid parameter length"],
        ['OperateType','length:0,100',"OperateType Invalid parameter length"],
        ['Description','length:0,500',"Description Invalid parameter length"],
        ['RefID',     'number',        "RefID Must be a number"],
        ['ErrorInfo',    'length:0,500',"ErrorInfo Invalid parameter length"],
        ['BatchNumber',    'number',        "BatchNumber Must be a number"],
        ['ActivityType',    'length:0,20',        "ActivityType Invalid parameter length"],
        ['OperationType',    'number',        "OperationType Must be a number"],
        ['WebsiteURL',    'url',        "WebsiteURL Invalid"],
        ['Active',    'in:0,1',        "Active Invalid"],
        ['CommissionRate',    'between:0,1',        "CommissionRate value is between 0 and 1."],
        ['Partner',     'number|length:1,20',        "Partner Must be a number|Partner Length must be between 1-20"],
        ['Notes',    'length:0,500',"Notes Invalid parameter length"],
        ['LevelIndex',    'between:0,10',        "LevelIndex value is between 0 and 10."],
        ['LevelID',    'number',        "LevelID Must be a number"],
        ['OldLevelIndex',    'between:0,10',        "OldLevelIndex value is between 0 and 10."],
        ['NewLevelIndex',    'between:0,10',        "NewLevelIndex value is between 0 and 10."],
    ];
    protected $scene = [
        'LoginForToken'   =>  ['AccountName',"SiteID","Password"],
        'getCustomerByToken'   =>  ['token'],
        'GetCustomerInfoByAccount'  =>  ['AccountName'],
        'getCustomerByID'  =>  ['ID'],
        'getCustomerList'  =>  ['RegisterStart','RegisterEnd','BirthdayStart','BirthdayEnd','CountryCode'],
        'updateStatus'  =>  ['ID','Remarks','Status'],
        'validateCustomer'  =>  ['Email'],
        'registerCustomer'  =>  ['Email','FirstName','LastName','SiteID','SourceType'],
        'saveProfile'  =>  ['ID','Email','Status','Password','FirstName','LastName','Gender','CountryCode','PhotoPath','Birthday'],
        'changePassword'  =>  ['ID','New_Password','Old_Password'],
        'checkPaymentPassword'  =>  ['CustomerID','PaymentPassword'],
        'changeEmail'  =>  ['ID','AccountName','Password','Email'],
        'PaymentPassword'  =>  ['CustomerID','PaymentPassword'],
        'confirmPaymentPassword'  =>  ['CustomerID','Password'],
        'passwordFind'  =>  ['Email'],
        'getAdminCustomerInfo'  =>  ['ID'],
        'autoRegisterCustomer'  =>  ['Email'],
        'getAdminCustomerData'  =>  ['user_data','field_type'],
        'confirmScPaymentPassword'  =>  ['CustomerID','Password'],
        'getUpdateTime'  =>  ['ID'],
        'addCustomerOther' => ['CustomerID','BrowserAttr','BrowserVersion','system','IPAddress','Country','Province','City'],
        'addSystemLog' => ['CustomerID','IPAddress','OperationName','DataCategory','OperateType','Description'],
        'addErrorLog' => ['RefID','Email','ErrorInfo','BatchNumber','ActivityType','OperationType'],
        'openAffiliate' => ['CustomerID','Email','Active','CommissionRate','Partner','Notes','LevelIndex'],
        'addAffiliateLevelLog' => ['LevelID','OldLevelIndex','NewLevelIndex','CommissionRate','Notes'],
        'activeAffiliateLevel' => ['ID','Active'],
        'editAffiliateLevel' => ['ID','CommissionRate','Notes','LevelIndex'],
        'editAffiliateEmail' => ['ID','CustomerID','Email'],
        'updatePhotoPath' => ['ID'],
    ];
	 /*protected $rule = [
         ['nickname',     'require|length:1,100',                    '昵称长度需在6-21个字符之间'],
        ['account',     'require|unique:Admin|alphaDash|length:6,30|regex:^[a-zA-z]+\w+',                        '帐号不能为空|帐号已存在|帐号只允许字母、数字和下划线 破折号|帐号长度为5-50个字符|帐号必须以字母开头'],
        ['nickname',     'length:6,30',                    '昵称长度需在6-21个字符之间'],
        ['password',    'require|length:6,30',                          '密码不能为空','密码长度需在6-21个字符之间'],
        ['phone',       ['regex'=>'/^1[3|4|5|7|8][0-9]{9}$/','unique:Admin','require'],    '手机格式错误|手机号已存在|手机号不能为空'],
        ['email',       'email',                       '邮箱格式错误'],
        ['AccountName',       ['regex'=>'/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&._-])[A-Za-z\d$@$!%*?&._-]{6,20}/','require'],    'Incorrect payment password format|Payment password can not be empty'],
    ];    */
}