<?php

return[
    //国家编码=>货币
    "Currency" =>[
        [
            'Code'=>'$',
            'Name'=>'USD'
        ],
        [
            'Code'=>'£',
            'Name'=>'GBP'
        ],
        [
            'Code'=>'CA$',
            'Name'=>'CAD'
        ],
        [
            'Code'=>'€',
            'Name'=>'EUR'
        ],
        [
            'Code'=>'R$',
            'Name'=>'BRL'
        ],
        [
            'Code'=>'RUB',
            'Name'=>'RUB'
        ],
        [
            'Code'=>'AU$',
            'Name'=>'AUD'
        ],
        [
            'Code'=>'CZK',
            'Name'=>'CZK'
        ],
        [
            'Code'=>'CLP',
            'Name'=>'CLP'
        ],
        [
            'Code'=>'JPY',
            'Name'=>'JPY'
        ],
        [
            'Code'=>'ILS',
            'Name'=>'ILS'
        ],
        [
            'Code'=>'ARS',
            'Name'=>'ARS'
        ],
        [
            'Code'=>'UAH',
            'Name'=>'UAH'
        ],
        [
            'Code'=>'TRY',
            'Name'=>'TRY'
        ],
        [
            'Code'=>'CHF',
            'Name'=>'CHF'
        ],
        [
            'Code'=>'R',
            'Name'=>'ZAR'
        ],
        [
            'Code'=>'kr',
            'Name'=>'DKK'
        ],
        [
            'Code'=>'kr',
            'Name'=>'NOK'
        ],
        [
            'Code'=>'kr',
            'Name'=>'SEK'
        ],
        [
            'Code'=>'Rs',
            'Name'=>'INR'
        ],
        [
            'Code'=>'S$',
            'Name'=>'SGD'
        ],
        [
            'Code'=>'Mex$',
            'Name'=>'MXN'
        ],
        [
            'Code'=>'원',
            'Name'=>'KRW'
        ],
        [
            'Code'=>'PLN',
            'Name'=>'PLN'
        ]
    ],
    //语种=>名称
    "Language" =>[
        [
            'Code'=>'en',
            'Name'=>'English'
        ],
        [
            'Code'=>'es',
            'Name'=>'Español'
        ],
        [
            'Code'=>'pt',
            'Name'=>'Português'
        ],
        [
            'Code'=>'ru',
            'Name'=>'Русский'
        ],
        [
            'Code'=>'de',
            'Name'=>'Deutsch'
        ],
        [
            'Code'=>'fr',
            'Name'=>'Français'
        ],
        [
            'Code'=>'nl',
            'Name'=>'Nederlands'
        ],
        [
            'Code'=>'cs',
            'Name'=>'Čeština'
        ],
        [
            'Code'=>'fi',
            'Name'=>'Suomi'
        ],
        [
            'Code'=>'it',
            'Name'=>'Italiano'
        ],
        [
            'Code'=>'no',
            'Name'=>'Norsk'
        ],
        [
            'Code'=>'sv',
            'Name'=>'Svenska'
        ],
        [
            'Code'=>'ja',
            'Name'=>'日本語'
        ],
        [
            'Code'=>'ar',
            'Name'=>'عربى'
        ]
    ],
    //币种URL
    "currency_url" => 'https://api.dx.com/share/ExchangeRate/rates'
//    "currency_url" => 'https://ers.dealextreme.com/api/rates'
];