<?php

/** payment结果返回 start **/
defined('PAYMENT_RESULT_STATUS_SUCCESS') or define('PAYMENT_RESULT_STATUS_SUCCESS', 'success');
defined('PAYMENT_RESULT_STATUS_PENDING') or define('PAYMENT_RESULT_STATUS_PENDING', 'pending');
defined('PAYMENT_RESULT_STATUS_FAILURE') or define('PAYMENT_RESULT_STATUS_FAILURE', 'failure');
/** payment结果返回 end **/

//交易来源定义
defined('TRANSACTION_SOUCE_DX_WEB') or define('TRANSACTION_SOUCE_DX_WEB', 'dxWeb');
defined('TRANSACTION_SOUCE_DX_APP') or define('TRANSACTION_SOUCE_DX_APP', 'dxApp');
/** payment支付渠道返回 start **/
defined('TRANSACTION_CHANNEL_EGP') or define('TRANSACTION_CHANNEL_EGP', 'egp');
defined('TRANSACTION_CHANNEL_IDEAL') or define('TRANSACTION_CHANNEL_IDEAL', 'ideal');
defined('TRANSACTION_CHANNEL_ASIABILL') or define('TRANSACTION_CHANNEL_ASIABILL', 'asiabill');
defined('TRANSACTION_CHANNEL_PAGSMILE') or define('TRANSACTION_CHANNEL_PAGSMILE', 'pagsmile');
defined('TRANSACTION_CHANNEL_PAYPAL') or define('TRANSACTION_CHANNEL_PAYPAL', 'paypal');
defined('TRANSACTION_CHANNEL_SC') or define('TRANSACTION_CHANNEL_SC', 'sc');
defined('TRANSACTION_CHANNEL_ASTROPAY') or define('TRANSACTION_CHANNEL_ASTROPAY', 'astropay');
/** payment支付渠道 end **/


//货币类型定义
defined('PAYMENT_CURRENCY_TYPE_CASH') or define('PAYMENT_CURRENCY_TYPE_CASH', 'cash');
defined('PAYMENT_CURRENCY_TYPE_STORECREDIT') or define('PAYMENT_CURRENCY_TYPE_STORECREDIT', 'storeCredit');

/** payment支付类型定义 start **/
defined('TRANSACTION_TYPE_PAYPAL') or define('TRANSACTION_TYPE_PAYPAL', 'paypal');
defined('TRANSACTION_TYPE_CREDITCARD') or define('TRANSACTION_TYPE_CREDITCARD', 'creditcard');
defined('TRANSACTION_TYPE_CREDITCARD_TOKEN') or define('TRANSACTION_TYPE_CREDITCARD_TOKEN', 'creditcard-token');
defined('TRANSACTION_TYPE_IDEAL') or define('TRANSACTION_TYPE_IDEAL', 'ideal');
defined('TRANSACTION_TYPE_SC') or define('TRANSACTION_TYPE_SC', 'sc');
defined('TRANSACTION_TYPE_ASTROPAY_ONLINE') or define('TRANSACTION_TYPE_ASTROPAY_ONLINE', 'AstropayTransfer');
defined('TRANSACTION_TYPE_ASTROPAY_CASH') or define('TRANSACTION_TYPE_ASTROPAY_CASH', 'AstropayBoleto');
defined('TRANSACTION_TYPE_ASTROPAY_CREDIT_CARD') or define('TRANSACTION_TYPE_ASTROPAY_CREDIT_CARD', 'AstropayCreditCard');
/** payment支付类型定义 end **/

/** 支付账号配置 start **/
defined('TRANSACTION_PAYMENT_ACCOUNT_ID_IDEAL') or define('TRANSACTION_PAYMENT_ACCOUNT_ID_IDEAL', 7);
defined('TRANSACTION_PAYMENT_ACCOUNT_ID_SC') or define('TRANSACTION_PAYMENT_ACCOUNT_ID_SC', 5);
defined('TRANSACTION_PAYMENT_ACCOUNT_ID_APP') or define('TRANSACTION_PAYMENT_ACCOUNT_ID_APP', 8);
defined('TRANSACTION_PAYMENT_ACCOUNT_ID_EGP') or define('TRANSACTION_PAYMENT_ACCOUNT_ID_EGP', 6);
defined('TRANSACTION_PAYMENT_ACCOUNT_ID_ASTROPAY') or define('TRANSACTION_PAYMENT_ACCOUNT_ID_ASTROPAY', 3);
defined('TRANSACTION_PAYMENT_ACCOUNT_ID_ASIABILL') or define('TRANSACTION_PAYMENT_ACCOUNT_ID_ASIABILL', 1);
defined('TRANSACTION_PAYMENT_ACCOUNT_ID_PAYPAL') or define('TRANSACTION_PAYMENT_ACCOUNT_ID_PAYPAL', 4);
defined('TRANSACTION_PAYMENT_ACCOUNT_ID_PAYSSION') or define('TRANSACTION_PAYMENT_ACCOUNT_ID_PAYSSION', 9);

/** 支付账号配置 end **/
